#!/usr/bin/env bash
bash -x util.sh              # 打印所有执行的命令
set -x                       # 打印执行的命令
set -u                       # 未定义的变量报错
set -e                       # 有错误就停止

# set -e不适用于管道
# 管道中一个错误，整个管道就算失败
set -o pipefail

(ping www.ibm.com &)         # 后台运行程序

# bash 多行注释
# 要定格
<<COMMENT             
...
COMMENT


for f in $(ls -d /usr/lib/*); do sudo ln -s $f /usr/lib/x86_64-linux-gnu;done    
#把/usr/lib的文件都软连接到x86_64-linux-gnu里

fc -2                        # 修改1条之前的命令
stat <filename>              # 查看access、modify、change time
look                         # 在/usr/share/dict/words中查找单词
dmesg -wh                    # 打开dmesg的正确姿势
rev                          # 反转字符串
rm !(*.tex|*.pdf)            # deletes all except the tex and pdf files.

# equal to `sort | uniq`
# but without sort and keep order
awk ' !x[$0]++' file3

#把wasm的hex打印出来，需要头部加上0x，尾部处理%
od  -tx1 hello.wasm | awk '{$1=""}1'  | tr -d " \n"

# ag openWindow | vim -        # 然后用gf跳转到文件

wc < a.txt                   # 用在脚本里,不会输出文件名

#以下是一些需要额外装的命令或者冷门命令,挺有用的
shellcheck                   # write better shell code
aspell check my.txt          # 交互式的拼写检查
fpp                          # 其实没怎么用过
xev                          # 查看键盘组合键的编码,参见 https://pavelmakhov.com/2016/06/awesome-wm-fn-keys/
notify-send                  # 桌面提醒
mdbook                       # 类似于GitBook
vidir                        # moreutils 里的东西
xxd                          # 不要用od hexdump
tidy                         # format html/xml
fx                           # interactive json viewer
whence                       # similar to which
                             # which = whence -c
dia                          # processon
nmtui                        # 终端连网络
scrcpy                       # 屏幕连手机
viu                          # terminal view image
parcellite                   # clipboard manager
flameshot                    # 截图软件
